create table
  public.clients (
    id bigint generated by default as identity,
    created_at timestamp without time zone null,
    email text not null,
    cpf text not null,
    name character varying(255) null,
    constraint Clients_pkey primary key (id),
    constraint Clients_Email_key unique (email),
    constraint Clients_cpf_key unique (cpf)
  ) tablespace pg_default;